<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="OpcUaDefinition" nsURI="http://at.pro2future/shopfloors/opcUaDefinition"
    nsPrefix="at.pro2future.shopfloors.opcUaDefinition">
  <eClassifiers xsi:type="ecore:EClass" name="MsMethodNode" eSuperTypes="#//MsNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userExecutalbe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputArguments" upperBound="-1"
        eType="#//MsVariableNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputArguments" upperBound="-1"
        eType="#//MsVariableNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="method" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsNode" abstract="true">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="MomentInterval"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeMask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userWriteMask" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nodeId" lowerBound="1"
        eType="#//MsNodeId" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="description" eType="#//MsLocalizedText"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="displayName" eType="#//MsLocalizedText"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="browseName" eType="#//MsQualifiedName"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsPropertyNode" eSuperTypes="#//MsVariableNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="MsViewNode" eSuperTypes="#//MsNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containsNoLoops" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventNotifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsReferenceTypeNode" eSuperTypes="#//MsNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="symmetric" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inverseName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsVariableNode" abstract="true" eSuperTypes="#//MsNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueRank" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userAccessLevel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minimumSamplingInterval"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="historizing" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" eType="#//MsNodeId"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasModellingRule" eType="#//MsNodeId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsObjectTypeNode" eSuperTypes="#//MsNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasComponent" upperBound="-1"
        eType="#//MsNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSubtype" upperBound="-1"
        eType="#//MsObjectTypeNode" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsVariableTypeNode" eSuperTypes="#//MsNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueRank" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsDataTypeNode" eSuperTypes="#//MsNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsObjectNode" eSuperTypes="#//MsNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasComponent" upperBound="-1"
        eType="#//MsNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventNotifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasTypeDefinition" lowerBound="1"
        eType="#//MsObjectTypeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasProperty" upperBound="-1"
        eType="#//MsPropertyNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="organizes" upperBound="-1"
        eType="#//MsNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasModellingRule" eType="#//MsNodeId"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsDataVariableNode" eSuperTypes="#//MsVariableNode"/>
  <eClassifiers xsi:type="ecore:EClass" name="MsNodeId">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Identifier" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespaceIndex" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowOverrideNamespaceIndex"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsLocalizedText">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MsQualifiedName">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="namespaceIndex" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShortObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
